# Generated by Django 2.2.3 on 2019-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='measurement',
            field=models.CharField(max_length=20),
        ),
    ]
